---
- name: Show Alarms definition
  debug:
    var: i_alarm

- set_fact:
    ec2_resources: []

- block:
    - name: "Setup {{i_alarm.name}} | Lookup EC2 instances"
      ec2_remote_facts:
        filters: "{{ i_alarm.filter_ec2_fact }}"
      register: resource_filtered

    - name: "Setup {{i_alarm.name}} | Show resources"
      debug: var=resource_filtered

    - name: "Setup {{i_alarm.name}} | Set resources"
      set_fact:
          ec2_resources: "{{ ec2_resources + [{'name': item.tags.Name, 'id': item.id}] }}"
      with_items: "{{ resource_filtered.instances }}"
      when: resource_filtered.instances is defined
  when: i_alarm.filter_type is defined and i_alarm.filter_type == 'ec2_fact'

- block:
    - name: "Setup {{i_alarm.name}} | Default lookup - static resources"
      set_fact:
          ec2_resources: "{{ ec2_resources + [{'name': item.name, 'id': item.id}] }}"
      with_items: "{{ i_alarm.ec2_resources }}"
      when: i_alarm.ec2_resources is defined
  when: i_alarm.filter_type is not defined

- name: "Setup {{i_alarm.name}} | Add alarm metric for each resource"
  ec2_metric_alarm:
    state: present
    region: "{{ i_alarm.region }}"
    name: "{{ item.name }}-{{ i_alarm.name }}"
    description: "{{ i_alarm.name }}-{{ item.name }} - Created by ansible"
    metric: "{{ i_alarm.metric }}"
    namespace: "{{ i_alarm.namespace }}"
    statistic: "{{ i_alarm.statistic }}"
    comparison: "{{ i_alarm.comparison }}"
    threshold: "{{ i_alarm.threshold }}"
    period: "{{ i_alarm.period }}"
    evaluation_periods: "{{ i_alarm.evaluation_periods }}"
    unit: "{{ i_alarm.unit }}"
    dimensions: {'InstanceId':"{{ item.id }}"}
    alarm_actions: "{{ i_alarm.alarm_actions }}"
    insufficient_data_actions: "{{ i_alarm.insufficient_data_actions }}"
    ok_actions: "{{ i_alarm.ok_actions }}"
  with_items: "{{ ec2_resources }}"
  when: i_alarm.namespace == "AWS/EC2"
