---
- debug: var=i_alarm

# Only support lookup by ec2_tag
- name: "Setup {{i_alarm.name}} | Getting resources"
  ec2_remote_facts:
    filters:
      "tag:ansible_host": "{{ item }}"
  when: i_alarm.filter_type == 'ec2_tag'
  with_items: "{{ i_alarm.filter_host }}"
  register: resource_filtered

- name: "Setup {{i_alarm.name}} | Show resources"
  debug: var=resource_filtered

- name: "Setup {{i_alarm.name}} | Add alarm metric for each resource"
  ec2_metric_alarm:
    state: present
    region: "{{ i_alarm.region }}"
    name: "{{ item.tags.Name }}-{{ i_alarm.name_sufix }}"
    description: "{{ item.tags.Name }}-{{ i_alarm.name_sufix }} - Created by ansible"
    metric: "{{ i_alarm.metric }}"
    namespace: "{{ i_alarm.namespace }}"
    statistic: "{{ i_alarm.statistic }}"
    comparison: "{{ i_alarm.comparison }}"
    threshold: "{{ i_alarm.threshold }}"
    period: "{{ i_alarm.period }}"
    evaluation_periods: "{{ i_alarm.evaluation_periods }}"
    unit: "{{ i_alarm.unit }}"
    dimensions: {'InstanceId':"{{ item.id }}"}
    alarm_actions: "{{ i_alarm.alarm_actions }}"
    insufficient_data_actions: "{{ i_alarm.insufficient_data_actions }}"
    ok_actions: "{{ i_alarm.ok_actions }}"
  with_items: "{{ resource_filtered.results[0].instances }}"
  when: i_alarm.namespace == "AWS/EC2"
